openapi: '3.0.2'
info:
  title: UpSport
  description: Projet réalisé dans le cadre du cours de Web Architecture 4eiaw40 à l'ECAM (Buslain Alexandre)
  version: '1.0'
servers:
  - url: http://localhost:3000
  - url: https://api.server.test/v1
  

#ACCORD
paths:
  /accords:
    get:
      tags:
      - Accord
      summary: Renvoie tous les accords
      responses:
        '200':
          description: A JSON array of destinations
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/accords'


  /accords?id={accord_id}:
    get:
      tags:
      - Accord
      summary: renvoie un accord identifié par son id
      parameters:
        - name: accord_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of destination
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/accord'

    delete:
      tags:
      - Accord
      summary: Supprime un accord
      parameters:
        - name: accord_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'

    put: 
      tags:
      - Accord
      summary: Modifie un accord
      parameters:
        - name: accord_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
                

  /accords/add:
    post:
      tags:
      - Accord
      summary: Ajoute/Crée un accord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/accord'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'


  /accords/search?term={term}:
    get:
      tags:
      - Accord
      summary: Chercher avec un term et obtenir les accords correspondants
      parameters:
        - name: term
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: string
            minimum: 1
            example: XXX
      responses:
        '200':
          description: A JSON dict of destination
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/accords'



# CONTREPARTIE
  /accords/contrepartie:
    get:
      tags:
      - Contrepartie
      summary: Renvoie toutes les contreparties
      responses:
        '200':
          description: A JSON array of destinations
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/contreparties'


  /accords/contrepartie?id={contrepartie_id}:
    get:
      tags:
      - Contrepartie
      summary: Renvoie les infos d'une contrepartie identifiée par son id
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Agency
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/contrepartie'
    delete:
      tags:
      - Contrepartie  
      summary: Supprime une contrepartie
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
    post:
      tags:
      - Contrepartie
      summary: Valide une contrepartie
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'


# ATHLETE
  /athletes:
    get:
      tags:
       - Athlete
      summary: Renvoie tous les Athletes
      responses:
        '200':
          description: A JSON array of links
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/athletes'
  /athletes/add:
    post:
      tags:
       - Athlete
      summary: Crée un nouvel Athlete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/athlete'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
    
  /athletes?id={id}:
    get:
      tags:
      - Athlete 
      summary: Renvoie un Athlete identifié par son id
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Link
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/athlete'
    delete:
      tags:
      - Athlete  
      summary: Supprime un Athlete
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'

# SPONSOR
  /sponsors:
    get:
      tags:
       - Sponsor
      summary: Renvoie tous les sponsors
      responses:
        '200':
          description: A JSON array of links
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/sponsors'
  /sponsors/add:
    post:
      tags:
       - Sponsor
      summary: Crée un nouveau sponsor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/sponsor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
    
  /sponsors?id={id}:
    get:
      tags:
      - Sponsor 
      summary: Renvoie un sponsor identifié par son id
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Link
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/sponsor'
    delete:
      tags:
      - Sponsor  
      summary: Supprime un sponsor
      parameters:
        - name: id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'




#COMPONENTS
components:
  schemas:

    GoodResponse:
      description: A good response
      properties:
        message: 
          type: string
          example: Operation done
    
    accord:
      description: Modèle contenant l'info de l'accord
      properties:
      
        sponsor:
          type: string
          example: Red Bull
        athlete:
          type: string
          example: Tom de Dorlodot
        date_signature:
          type: string
          example: 22/10/1997
        date_fin:
          type: string
          example: 23/10/2025
        
    accords:
      description: Modèle contenant plusieurs accords
      items:
        type: object         
        $ref: '#/components/schemas/accord'



    contrepartie:
      description: Modèle contenant l'info d'une contrepartie
      properties:

        etat_avancement: 
          type: string
          example: done
        statut:
          type: boolean
          example: true
          
    contreparties:
      description: Modèle contenant plusieurs contreparties
      items:
        type: object         
        $ref: '#/components/schemas/contrepartie'



    athlete:
      description: Modèle contenant l'info d'un Athlete
      properties:

        nom: 
          type: string
          example: de Dorlodot
        prenom:
          type: string
          example: Tom
        discipline:
          type: string
          example: parapente
        adresse:
          type: string
          example: rue du vent

     
    athletes:
      description: Modèle contenant plusieurs Athletes
      items:
        type: object         
        $ref: '#/components/schemas/athlete'


    sponsor:
      description: Modèle contenant l'info d'un sponsor
      properties:

        nom: 
          type: string
          example: Red Bull
        adresse:
          type: string
          example: Avenue du lac
     
    sponsors:
      description: Modèle contenant plusieurs sponsors
      items:
        type: object         
        $ref: '#/components/schemas/sponsor'