openapi: '3.0.2'
info:
  title: UpSport
  description: Projet réalisé dans le cadre du cours de Web Architecture 4eiaw40 à l'ECAM (Buslain Alexandre)
  version: '1.0'
servers:
  - url: http://localhost:3000
  # - url: https://api.server.test/v1
  
paths:

#ACCORD
  /accords:
    get:
      tags:
        - Accord
      summary: Renvoie tous les accords
      responses:
        '200':
          description: Un tableau JSON d'accords
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/accords'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'


    post:
      tags:
        - Accord
      summary: Ajoute/Crée un accord
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/accord'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
            description: Not OK
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/BadResponse'


### /accords?id={accord_id}:
  /accords/{accord_id}:
    get:
      tags:
        - Accord
      summary: renvoie un accord identifié par son id
      parameters:
        - name: accord_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of destination
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/accord'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    delete:
      tags:
        - Accord
      summary: Supprime un accord identifié par son id
      parameters:
        - in: path
          name: accord_id
          required: true
          schema:
            type: integer
            example: 22
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'


# CONTREPARTIE
  /contreparties:
    get:
      tags:
        - Contrepartie
      summary: Renvoie toutes les contreparties
      responses:
        '200':
          description: A JSON array of destinations
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/contreparties'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    post:
        tags:
          - Contrepartie
        summary: Ajoute/Crée une contrepartie
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/contrepartie'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  $ref: '#/components/schemas/GoodResponse'
          '400':
              description: Not OK
              content:
                application/json:
                  schema:
                    type: object
                    $ref: '#/components/schemas/BadResponse'



  /contreparties/{contrepartie_id}:
    get:
      tags:
        - Contrepartie
      summary: Renvoie les infos d'une contrepartie identifiée par son id
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of contrepartie
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/contrepartie'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    delete:
      tags:
        - Contrepartie  
      summary: Supprime une contrepartie
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    put:
      tags:
        - Contrepartie
      summary: Valide une contrepartie
      parameters:
        - name: contrepartie_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: '#/components/schemas/contrepartie'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'


# ATHLETE
  /athletes:
    get:
      tags:
        - Athlete
      summary: Renvoie tous les Athletes
      responses:
        '200':
          description: A JSON array of links
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/athletes'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    post:
      tags:
        - Athlete
      summary: Crée un nouvel Athlete
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/athlete'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'
    
  /athletes/{athlete_id}:
    get:
      tags:
        - Athlete 
      summary: Renvoie un Athlete identifié par son id
      parameters:
        - name: athlete_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Link
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/athlete'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    put:
      tags:
        - Athlete
      summary: Modifie un athlète identifié par son id
      parameters:
        - in: path
          name: athlete_id
          required: true
          schema:
            type: integer
            example: 234
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/athlete'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'


    delete:
      tags:
        - Athlete  
      summary: Supprime un Athlete
      parameters:
        - name: athlete_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

# SPONSOR
  /sponsors:
    get:
      tags:
        - Sponsor
      summary: Renvoie tous les sponsors
      responses:
        '200':
          description: A JSON array of links
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/sponsors'
    post:
      tags:
        - Sponsor
      summary: Crée un nouveau sponsor
      requestBody:
        required: true
        content:
          application/json:
            schema:
                type: array
                $ref: '#/components/schemas/sponsor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'
    
  /sponsors/{sponsor_id}:
    get:
      tags:
        - Sponsor 
      summary: Renvoie un sponsor identifié par son id
      parameters:
        - name: sponsor_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Link
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/sponsor'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    put:
      tags:
        - Sponsor
      summary: Modifie un sponsor identifié par son id
      parameters:
        - in: path
          name: sponsor_id
          required: true
          schema:
            type: integer
            example: 2345
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              $ref: '#/components/schemas/sponsor'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'


    delete:
      tags:
        - Sponsor  
      summary: Supprime un sponsor
      parameters:
        - in: path
          name: sponsor_id
          required: true
          schema:
            type: integer
            example: 199
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'



  # LINKS
  /links:
    get:
      tags:
        - Lien  
      summary: Obtenir tous les liens
      responses:
        '200':
          description: Un tableau JSON de liens
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Links'
    post:
      tags:
        - Lien  
      summary: Ajouter un nouveau lien
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Link'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

      
  /links/{link_id}:
    get:
      tags:
        - Lien  
      summary: Renvoie l'info d'un lien identifié par son id
      parameters:
        - name: link_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A JSON dict of Link
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Link'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'

    delete:
      tags:
        - Lien  
      summary: Supprime un lien
      parameters:
        - name: link_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 3
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GoodResponse'
        '400':
          description: Not OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/BadResponse'




#COMPONENTS
components:
  schemas:

    GoodResponse:
      description: A good response
      properties:
        message: 
          type: string
          example: Operation done

    BadResponse:
      description: A bad response
      properties:
        message: 
          type: string
          example: Operation not done
    
    accord:
      description: Modèle contenant l'info de l'accord
      properties:
      
        sponsor:
          type: string
          example: Red Bull
        athlete:
          type: string
          example: Tom de Dorlodot
        date_signature:
          type: string
          format: date
          example: "1997-10-22"
        date_fin:
          type: string
          format: date
          example: "2025-10-22"
        
    accords:
      description: Modèle contenant plusieurs accords
      items:
        type: object         
        $ref: '#/components/schemas/accord'



    contrepartie:
      description: Modèle contenant l'info d'une contrepartie
      properties:

        description:
          type: string
          example: Poster 10 photos sur Instagram par mois
        etat_avancement: 
          type: string
          example: done
        statut:
          type: boolean
          example: true
          
    contreparties:
      description: Modèle contenant plusieurs contreparties
      items:
        type: object         
        $ref: '#/components/schemas/contrepartie'


    athlete:
      description: Modèle contenant l'info d'un Athlete
      properties:

        nom: 
          type: string
          example: de Dorlodot
        prenom:
          type: string
          example: Tom
        discipline:
          type: string
          example: parapente
        adresse:
          type: string
          example: rue du vent

     
    athletes:
      description: Modèle contenant plusieurs Athletes
      items:
        type: object         
        $ref: '#/components/schemas/athlete'


    sponsor:
      description: Modèle contenant l'info d'un sponsor
      properties:

        nom: 
          type: string
          example: Red Bull
        adresse:
          type: string
          example: Avenue du lac
     
    sponsors:
      description: Modèle contenant plusieurs sponsors
      items:
        type: object         
        $ref: '#/components/schemas/sponsor'


    Link:
      description: Modèle contenant l'info d'un lien
      properties:

        accord_id:
          type: string
          example: "1"
        contrepartie_id:
          type: string
          example: "1"
    Links:
      description: Modèle contenant plusieurs liens
      items:
        type: object         
        $ref: '#/components/schemas/Link'